spring.application.name=orquestrador-service
server.port=8084

# URLs dos servicos internos
cliente.service.url=http://localhost:8081/api/clientes
conta.service.url=http://localhost:8082/api/contas
movimentos.service.url=http://localhost:8083/api/movimentos